[package]
name="tracker"
version="0.1.0"
edition="2021"
[dependencies]
actix-web="4"
serde={version="1",features=["derive"]}
sqlx={version="0.7",features=["sqlite","runtime-actix-native-tls"]}
serde_json="1"
